name: Funny Joke Action

on:
  push:
    branches:
      - main

jobs:
  tell-joke:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get a Random Joke
      run: |
        # Using curl to get a random joke from a public API
        joke=$(curl -s https://official-joke-api.appspot.com/random_joke)
        # Extract setup and punchline from JSON response and print them
        setup=$(echo $joke | jq -r '.setup')
        punchline=$(echo $joke | jq -r '.punchline')
        echo "Joke of the day: $setup"
        echo "Punchline: $punchline"
        echo "Now go ahead and push more code! :)"
